spring:
  application:
    name: chi-discovery-service
server:
  port: 8010
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8010/eureka