logging:
  level:
    root: INFO
  config: classpath:log4j-spring.xml
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  forward-headers-strategy: framework
spring:
  application:
    name: chi-discovery-service
eureka:
  instance:
    hostname: chi-discovery-service.herokuapp.com
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:}