logging:
  level:
    root: INFO
  config: classpath:log4j-spring.xml
server:
  port: 8010
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
#  http2:
#    enabled: true
#  ssl:
#    enabled: true
#    enabled-protocols: TLSv1.2
#    key-alias: ${SSL_KEY_ALIAS:}
#    key-password: ${SSL_KEY_PASSWORD:}
#    key-store: classpath:vengeance.jks
#    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
#    key-store-type: JKS
#    protocol: TLS
spring:
  application:
    name: chi-discovery-service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: true
    securePortEnabled: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    renewal-percent-threshold: 0.85
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:}
custom:
  trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:}
  trust-store-type: JKS